const fs = require('fs');
const crypto = require('crypto');
const path = require('path');

const ORIGINAL_TESTS = [
  { code: 'T0130', name: 'TSH (Ultra sensitive) CMIA Serum' },
  { code: 'C0017', name: 'Calcium Total Serum' },
  { code: 'B0038', name: 'Bilirubin Total, Direct, Indirect, Serum' },
  { code: 'C0106', name: 'Cholesterol Total Serum' },
  { code: 'C0169', name: 'Creatinine' },
  { code: 'R0029', name: 'Routine Examination Stool' },
  { code: 'R0041', name: 'Urine Routine' },
  { code: 'S0018', name: 'SGOT' },
  { code: 'S0019', name: 'SGPT' },
  { code: 'T0106', name: 'Triglycerides Serum' },
  { code: 'U0003', name: 'Urea' },
  { code: 'U0007', name: 'Uric Acid' },
  { code: 'S0032', name: 'Sodium' },
  { code: 'P0078', name: 'Potassium SE Serum' },
  { code: 'B0046', name: 'Blood Group' },
  { code: 'P0032', name: 'PBS (Peripheral Smear Examination) EDTA Blood' },
  { code: 'A0125', name: 'Albumin Serum' },
  { code: 'P0053', name: 'Phosphorus Serum' },
  { code: 'V0003', name: 'VDRL RPR Serum' },
  { code: 'W0011', name: 'Widal Test for Typhoid Serum' },
  { code: 'H0295', name: 'Histology Extra Slide Set' },
  { code: 'L0017', name: 'LDL Cholesterol Direct Serum' },
  { code: 'R0001', name: 'RA Test Rheumatoid Arthritis Serum' },
  { code: 'H0057', name: 'HDL Cholesterol Direct Serum' },
  { code: 'C0165', name: 'CPK Total Serum' },
  { code: 'H0018', name: 'HbA1c Blood' },
  { code: 'L0012', name: 'LDH Lactate Dehydrogenase Serum' },
  { code: 'P0110', name: 'Prothrombin Time (PT)' },
  { code: 'G0020', name: 'Gamma GT (CGTP) Serum' },
  { code: 'L0068', name: 'Lipase Serum' },
  { code: 'P0112', name: 'PSA Total Prostate Specific Antigen Serum' },
  { code: 'T0042', name: 'Testosterone Total Serum' },
  { code: 'L0080', name: 'Liver Function Test Mini' },
  { code: 'A0471', name: 'APTT' },
  { code: 'A0127', name: 'Albumin Creatinine Ratio Urine' },
  { code: 'R0012', name: 'Renal (Kidney) Function Tests Mini (Urea Rt, Creatinine, Uric)' },
  { code: 'F0018', name: 'Ferritin Serum' },
  { code: 'I0275', name: 'Insulin (Fasting) CMIA Serum' },
  { code: 'I0275_PP', name: 'Insulin Post Prandial Serum by ECLIA' },
  { code: 'A0031', name: 'ADA (Adenosine Deaminase) Serum' },
  { code: 'C0124', name: 'CPK MB Fraction' },
  { code: 'H0192', name: 'Histopathological Examination Unspecified Specimen Small' },
  { code: 'V0015', name: 'Vitamin D Total 25 Hydroxy Plasma Serum' },
  { code: 'C0197', name: 'Culture & Sensitivity Aerobic Bacteria Stool' },
  { code: 'C0047', name: 'CCP Antibody Serum' },
  { code: 'P0012', name: 'PAP Smear by Liquid Based Cytology (LBC)' },
  { code: 'H0191', name: 'Histopathological Examination Unspecified Specimen Medium' },
  { code: 'H0793', name: 'H3 Viral Marker Profile (HIV, HbsAg, HCV)' },
  { code: 'D0039', name: 'Maternal Screen (Dual Marker Test) First Trimester' },
  { code: 'P0088', name: 'Procalcitonin Serum' },
  { code: 'D0041', name: 'Maternal Screen (Triple Marker) 2nd Trimester Serum' },
  { code: 'T0077', name: 'TORCH 10 by CLIA Serum' },
  { code: 'K0012', name: 'Karyotyping by G Banding' },
  { code: 'A0001', name: 'Abnormal Haemoglobin Studies Blood' },
  { code: 'A0647', name: 'AFB DNA Detection by Realtime PCR Other Samples' },
  { code: 'A0084', name: 'AFB DNA Detection by Realtime PCR Sputum/BAL' },
  { code: 'A0119', name: 'AFP Alpha Fetoprotein Serum' },
  { code: 'A0417', name: 'AMH Mullerian Inhibitor Substance Serum' },
  { code: 'A0432', name: 'Amylase Serum' },
  { code: 'A0437', name: 'ANA Anti Nuclear Antibody by FA Serum' },
  { code: 'A0485', name: 'ASO Titre Serum' },
  { code: 'C0005', name: 'CA 12.5 Serum' },
  { code: 'C0007', name: 'CA 19.9 Serum' },
  { code: 'C0038', name: 'Cardiolipin Antibody IgG Serum' },
  { code: 'C0039', name: 'Cardiolipin Antibody IgM Serum' },
  { code: 'C0078', name: 'CEA Carcinoembryonic Antigen Serum' },
  { code: 'C0151', name: 'Coombs Direct (DAT) Test' },
  { code: 'C0152', name: 'Coombs Indirect (IAT) Test' },
  { code: 'C0157', name: 'Cortisol Serum (8AM)' },
  { code: 'C0157_4PM', name: 'Cortisol Serum (4PM)' },
  { code: 'C0170', name: 'CRP C-Reactive Protein Serum' },
  { code: 'C0182', name: 'Culture & Sensitivity Aerobic Bacteria Blood Single Bottle' },
  { code: 'C0202', name: 'Culture & Sensitivity (Automated) Aerobic Bacteria Urine' },
  { code: 'D0002', name: 'D Dimer Plasma' },
  { code: 'D0003', name: 'Dengue Antibody IgG Serum' },
  { code: 'D0004', name: 'Dengue Antibody IgM Serum' },
  { code: 'D0005', name: 'Dengue NS1 Antigen Serum' },
  { code: 'D0032', name: 'DNA (ds) Antibody (NCX) Serum' },
  { code: 'E0021', name: 'Electrolytes Serum' },
  { code: 'E0004', name: 'Estradiol (E2) Serum' },
  { code: 'F0046', name: 'Folic Acid Serum' },
  { code: 'F0058', name: 'FSH Follicle Stimulating Hormone Serum' },
  { code: 'H0040', name: 'HBsAg Screening Serum' },
  { code: 'H0043', name: 'HCG Beta Subunit Serum' },
  { code: 'H0055', name: 'HCV Hepatitis C Total Antibodies (Anti HCV) Serum' },
  { code: 'H0211', name: 'HIV DUO p24 Antigen & Antibody to HIV 1 & 2 Serum' },
  { code: 'H0250', name: 'HLA B27 (Human Leucocyte Antigen B27)' },
  { code: 'A0398', name: 'IgE Total Antibody Serum' },
  { code: 'I0373', name: 'IGRAS (Quantiferon TB Gold) 3 Tube Assay' },
  { code: 'I0286', name: 'Iron Studies Serum' },
  { code: 'L0066', name: 'LH Luteinizing Hormone CMIA Serum' },
  { code: 'L0071', name: 'Lipid Profile Mini' },
  { code: 'M0002', name: 'Magnesium Serum' },
  { code: 'D0040', name: 'Maternal Screen (Quadruple Test) 2nd Trimester' },
  { code: 'M0053', name: 'Microalbumin Creatinine Ratio' },
  { code: 'A0464', name: 'Phospholipid Antibody IgG Serum' },
  { code: 'A0465', name: 'Phospholipid Antibody IgM Serum' },
  { code: 'P0089', name: 'Progesterone (P4) CMIA Serum' },
  { code: 'P0090', name: 'Prolactin Serum' },
  { code: 'P0096', name: 'Protein Electrophoresis Serum' },
  { code: 'P0114', name: 'PTH Intact Molecule Parathyroid Hormone Serum/Plasma' },
  { code: 'T0065', name: 'Thyroid Panel 1 (T3/T4/TSH)' },
  { code: 'T0066', name: 'Thyroid Panel 2 (FT3, FT4, TSH)' },
  { code: 'T0068', name: 'Thyroid Panel 4 Thyroscreen FT4 And TSH 3rd Gen Serum' },
  { code: 'T0101', name: 'TPO (Thyroid Peroxidase) Antibody (AMA) Microsomal Antibody' },
  { code: 'T0135', name: 'Typhi Dot IgM Serum' },
  { code: 'V0010', name: 'Vitamin B12 Cyanocobalamin Serum' },
  { code: 'C0044', name: 'CBC' },
  { code: 'DL014', name: 'CBC + ESR' },
  { code: 'G0027', name: 'Glucose' },
  { code: 'G0027_F', name: 'Glucose PP' },
  { code: 'G0027_R', name: 'Glucose RBS' },
  { code: 'H0069', name: 'Haemoglobin' },
  { code: 'M0006', name: 'Malaria Parasite Detection by Smear Examination' },
  { code: 'M0010', name: 'Malaria Antigen Detection Vivax & Falciparum' },
  { code: 'P0063', name: 'Platelet Count / Thrombocyte Count Blood' },
  { code: 'C0204', name: 'Culture and Identification Anaerobic Bacteria Blood Single Bottle' }
];

const testsWithIds = ORIGINAL_TESTS.map(t => ({ id: crypto.randomUUID(), ...t }));
fs.writeFileSync(path.join(__dirname, 'data', 'tests.json'), JSON.stringify(testsWithIds, null, 2));
console.log('Created tests.json!');
